### ISSUE TITLE
Project Homepage link is dead

### ISSUE THREAD

**Issue by marek22k** [cloudflare/roughtime#29]
The repo currently links to https://developers.cloudflare.com/roughtime/, but this results in a 404 page. Maybe it should link to https://developers.cloudflare.com/time-services/roughtime/?
Alternatively or supplementing and so that also old links are preserved, one could set up a redirection.

**Comment by cjpatton** [comment]
Looks to be the new location for this, yeah. Mind sending a PR?

**Comment by marek22k** [comment]
I can do that. However, the URL is also specified as a repo homepage, which cannot be changed via PR.
