### ISSUE TITLE
Implement draft-ietf-ntp-roughtime-10

### ISSUE THREAD

**Issue by cjpatton** [cloudflare/roughtime#53]
The only substantive change since draft-08 is the new SRV tag, which we will want to implement:
https://author-tools.ietf.org/iddiff?url1=draft-ietf-ntp-roughtime-08&url2=draft-ietf-ntp-roughtime-10&difftype=--html

We could easily support draft 10 alongside draft 08 and Google Roughtime.

**Comment by vserdyuk** [comment]
draft-08:
> Servers SHOULD support the UDP transport mode, while TCP transport is OPTIONAL.

draft-10:
> Servers SHOULD support the UDP transport mode and TCP mode.

This also sounds like a substantive change.

**Comment by cjpatton** [comment]
HI @vserdyuk, we don't have plans to add TCP support to this repo. If you'd like to add it, we'd welcome a contribution. Please start by filing an issue describing the change set you'd want to implement.
